---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: Para instalar Astra Control Center después de tratar algunos requisitos previos medioambientales, descargará el paquete e instálelo siguiendo los pasos descritos. 
---
= Instalar Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Para instalar Astra Control Center, lleve a cabo los siguientes pasos:

* <<Instalar Astra Control Center>>
* <<Inicie sesión en la interfaz de usuario de Astra Control Center>>




== Instalar Astra Control Center

Para instalar Astra Control Center, descargue el paquete de instalación desde el sitio de soporte de NetApp y realice una serie de comandos para instalar Astra Control Center Operator y Astra Control Center en su entorno. Puede utilizar este procedimiento para instalar Astra Control Center en entornos conectados a Internet o con conexión por aire.

.Lo que necesitará
* link:requirements.html["Antes de comenzar la instalación, prepare su entorno para la implementación de Astra Control Center"].
* En el clúster OpenShift, asegúrese de que todos los operadores de clúster se encuentran en buen estado (`available` es `true`):
+
[listing]
----
oc get clusteroperators
----
* Desde su clúster OpenShift, asegúrese de que todos los servicios API se encuentran en buen estado (`available` es `true`):
+
[listing]
----
oc get apiservices
----


.Acerca de esta tarea
El proceso de instalación de Astra Control Center realiza lo siguiente:

* Instala los componentes de Astra en `netapp-acc` (o espacio de nombres personalizado).
* Crea una cuenta predeterminada.
* Establece una dirección de correo electrónico de usuario administrativo predeterminada y una contraseña única predeterminada de `ACC-<UUID_of_installation>` Por este ejemplo de Astra Control Center. A este usuario se le asigna el rol de propietario del sistema y es necesario iniciar sesión por primera vez en la interfaz de usuario.
* Le ayuda a determinar que se están ejecutando todas las pods de Astra Control Center.
* Instala la interfaz de usuario de Astra.



NOTE: Los comandos de Podman se pueden utilizar en lugar de los comandos de Docker si está utilizando el repositorio de Podman de Red Hat.

.Pasos
. Descargue el paquete Astra Control Center (`astra-control-center-[version].tar.gz`) del https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Sitio de soporte de NetApp"^].
. Descargue el archivo zip de los certificados y claves de Astra Control Center desde https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Sitio de soporte de NetApp"^].
. (Opcional) Use el siguiente comando para verificar la firma del paquete:
+
[listing]
----
openssl dgst -sha256 -verify astra-control-center[version].pub -signature <astra-control-center[version].sig astra-control-center[version].tar.gz
----
. Extraiga las imágenes:
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----
. Cambie al directorio Astra.
+
[listing]
----
cd astra-control-center-[version]
----
. Agregue los archivos del directorio imagen de Astra Control Center al registro local.
+

NOTE: Consulte una secuencia de comandos de ejemplo para la carga automática de imágenes a continuación.

+
.. Inicie sesión en su registro de Docker:
+
[listing]
----
docker login [Docker_registry_path]
----
.. Cargue las imágenes en Docker.
.. Etiquete las imágenes.
.. Inserte las imágenes en el registro local.


+
[listing]
----
export REGISTRY=[Docker_registry_path]
for astraImageFile in $(ls images/*.tar) ; do
  # Load to local cache. And store the name of the loaded image trimming the 'Loaded images: '
  astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
  astraImage=$(echo ${astraImage} | sed 's!localhost/!!')
  # Tag with local image repo.
  docker tag ${astraImage} ${REGISTRY}/${astraImage}
  # Push to the local repo.
  docker push ${REGISTRY}/${astraImage}
done
----
. (Sólo para registros con requisitos de autenticación) Si utiliza un registro que requiere autenticación, debe hacer lo siguiente:
+
.. Cree el `netapp-acc-operator` espacio de nombres:
+
[listing]
----
kubectl create ns netapp-acc-operator
----
+
Respuesta:

+
[listing]
----
namespace/netapp-acc-operator created
----
.. Cree un secreto para `netapp-acc-operator` espacio de nombres. Añada información sobre Docker y ejecute el siguiente comando:
+
[listing]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[Docker_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Respuesta de ejemplo:

+
[listing]
----
secret/astra-registry-cred created
----
.. Cree el `netapp-acc` (o espacio de nombres personalizado).
+
[listing]
----
kubectl create ns [netapp-acc or custom]
----
+
Respuesta de ejemplo:

+
[listing]
----
namespace/netapp-acc created
----
.. Cree un secreto para `netapp-acc` (o espacio de nombres personalizado). Añada información sobre Docker y ejecute el siguiente comando:
+
[listing]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom] --docker-server=[Docker_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Respuesta

+
[listing]
----
secret/astra-registry-cred created
----


. Edite la implementación del operador de Astra Control Center yaml (`astra_control_center_operator_deploy.yaml`) para referirse a su registro local y secreto.
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. Si utiliza un registro que requiere autenticación, reemplace la línea predeterminada de `imagePullSecrets: []` con lo siguiente:
+
[listing]
----
imagePullSecrets:
- name: astra-registry-cred
----
.. Cambiar `[Docker_registry_path]` para la `kube-rbac-prox` imagen a la ruta del registro en la que ha insertado las imágenes en un paso anterior.
.. Cambiar `[Docker_registry_path]` para la `acc-operator-controller-manager` imagen a la ruta del registro en la que ha insertado las imágenes en un paso anterior.


+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [Docker_registry_path]/kube-rbac-proxy:v0.5.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *image: [Docker_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
      *imagePullSecrets: []*
----
. Edite el archivo de recursos personalizados (CR) del Centro de control de Astra (`astra_control_center_min.yaml`):
+
[listing]
----
vim astra_control_center_min.yaml
----
+

NOTE: Si se requieren personalizaciones adicionales para su entorno, puede utilizar `astra_control_center.yaml` Como CR alternativo. `astra_control_center_min.yaml` Es la CR predeterminada y es adecuada para la mayoría de las instalaciones.

+

NOTE: Las propiedades configuradas por la CR no se pueden cambiar tras la implementación inicial de Astra Control Center.

+
.. Cambiar `[Docker_registry_path]` a la ruta de acceso del registro en la que ha insertado las imágenes en el paso anterior.
.. Cambie el `accountName` cadena al nombre que desea asociar a la cuenta.
.. Cambie el `astraAddress` Cadena al FQDN que desea utilizar en su navegador para acceder a Astra. No utilizar `http://` o. `https://` en la dirección. Copie este FQDN para utilizarlo en un <<Inicie sesión en la interfaz de usuario de Astra Control Center,paso posterior>>.
.. Cambie el `email` cadena en la dirección inicial predeterminada del administrador. Copie esta dirección de correo electrónico para su uso en un <<Inicie sesión en la interfaz de usuario de Astra Control Center,paso posterior>>.
.. Cambiar `enrolled` Para AutoSupport a. `false` para sitios sin conexión a internet o retención `true` para sitios conectados.
.. (Opcional) Añada un nombre `firstName` y apellidos `lastName` del usuario asociado con la cuenta. Este paso se puede realizar ahora o una versión posterior dentro de la interfaz de usuario.
.. (Opcional) cambie el `storageClass` Valor en otro recurso de la clase de almacenamiento de Trident, si es necesario para su instalación.
.. Si no está utilizando un registro que requiere autorización, elimine el `secret` línea.


+
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[Docker_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
----
. Instale el operador de Astra Control Center:
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
Respuesta de ejemplo:

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. Si todavía no lo ha hecho en un paso anterior, cree el `netapp-acc` espacio de nombres (o personalizado):
+
[listing]
----
kubectl create ns [netapp-acc or custom]
----
+
Respuesta de ejemplo:

+
[listing]
----
namespace/netapp-acc created
----
. Ejecute el siguiente parche para corregir link:https://docs.netapp.com/us-en/astra-control-center/release-notes/known-issues.html#Incorrect-ClusterRoleBinding-created-by-Astra-Control-Center-CRD-during-installation["vinculación de roles del clúster"].
. Instale Astra Control Center en `netapp-acc` (o su espacio de nombres personalizado):
+
[listing]
----
kubectl apply -f astra_control_center_min.yaml -n [netapp-acc or custom]
----
+
Respuesta de ejemplo:

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----
. Compruebe que todos los componentes del sistema se han instalado correctamente.
+
[listing]
----
kubectl get pods -n [netapp-acc or custom]
----
+
Cada pod debe tener el estado de `Running`. Pueden tardar varios minutos en implementar los pods del sistema.

+
Respuesta de ejemplo:

+
[listing]
----
NAME                                         READY   STATUS    RESTARTS   AGE
acc-helm-repo-5fdfff786f-gkv6z               1/1     Running   0          4m58s
activity-649f869bf7-jn5gs                    1/1     Running   0          3m14s
asup-79846b5fdc-s9s97                        1/1     Running   0          3m10s
authentication-84c78f5cf4-qhx9t              1/1     Running   0          118s
billing-9b8496787-v8rzv                      1/1     Running   0          2m54s
bucketservice-5fb876d9d5-wkfvz               1/1     Running   0          3m26s
cloud-extension-f9f4f59c6-dz6s6              1/1     Running   0          3m
cloud-insights-service-5676b8c6d4-6q7lv      1/1     Running   0          2m52s
composite-compute-7dcc9c6d6c-lxdr6           1/1     Running   0          2m50s
composite-volume-74dbfd7577-cd42b            1/1     Running   0          3m2s
credentials-75dbf46f9d-5qm2b                 1/1     Running   0          3m32s
entitlement-6cf875cb48-gkvhp                 1/1     Running   0          3m12s
features-74fd97bb46-vss2n                    1/1     Running   0          3m6s
fluent-bit-ds-2g9jb                          1/1     Running   0          113s
fluent-bit-ds-5tg5h                          1/1     Running   0          113s
fluent-bit-ds-qfxb8                          1/1     Running   0          113s
graphql-server-7769f98b86-p4qrv              1/1     Running   0          90s
identity-566c566cd5-ntfj6                    1/1     Running   0          3m16s
influxdb2-0                                  1/1     Running   0          4m43s
krakend-5cb8d56978-44q66                     1/1     Running   0          93s
license-66cbbc6f48-27kgf                     1/1     Running   0          3m4s
login-ui-584f7fd84b-dmdrp                    1/1     Running   0          87s
loki-0                                       1/1     Running   0          4m44s
metrics-ingestion-service-6dcfddf45f-mhnvh   1/1     Running   0          3m8s
monitoring-operator-78d67b4d4-nxs6v          2/2     Running   0          116s
nats-0                                       1/1     Running   0          4m40s
nats-1                                       1/1     Running   0          4m26s
nats-2                                       1/1     Running   0          4m15s
nautilus-9b664bc55-rn9t8                     1/1     Running   0          2m56s
openapi-dc5ddfb7d-6q8vh                      1/1     Running   0          3m20s
polaris-consul-consul-5tjs7                  1/1     Running   0          4m43s
polaris-consul-consul-5wbnx                  1/1     Running   0          4m43s
polaris-consul-consul-bfvl7                  1/1     Running   0          4m43s
polaris-consul-consul-server-0               1/1     Running   0          4m43s
polaris-consul-consul-server-1               1/1     Running   0          4m43s
polaris-consul-consul-server-2               1/1     Running   0          4m43s
polaris-mongodb-0                            2/2     Running   0          4m49s
polaris-mongodb-1                            2/2     Running   0          4m22s
polaris-mongodb-arbiter-0                    1/1     Running   0          4m49s
polaris-ui-6648875998-75d98                  1/1     Running   0          92s
polaris-vault-0                              1/1     Running   0          4m41s
polaris-vault-1                              1/1     Running   0          4m41s
polaris-vault-2                              1/1     Running   0          4m41s
storage-backend-metrics-69546f4fc8-m7lfj     1/1     Running   0          3m22s
storage-provider-5d46f755b-qfv89             1/1     Running   0          3m30s
support-5dc579865c-z4pwq                     1/1     Running   0          3m18s
telegraf-ds-4452f                            1/1     Running   0          113s
telegraf-ds-gnqxl                            1/1     Running   0          113s
telegraf-ds-jhw74                            1/1     Running   0          113s
telegraf-rs-gg6m4                            1/1     Running   0          113s
telemetry-service-6dcc875f98-zft26           1/1     Running   0          3m24s
tenancy-7f7f77f699-q7l6w                     1/1     Running   0          3m28s
traefik-769d846f9b-c9crt                     1/1     Running   0          83s
traefik-769d846f9b-l9n4k                     1/1     Running   0          67s
trident-svc-8649c8bfc5-pdj79                 1/1     Running   0          2m57s
vault-controller-745879f98b-49c5v            1/1     Running   0          4m51s
----
. (Opcional) para asegurarse de que la instalación ha finalizado, puede ver el `acc-operator` registra utilizando el siguiente comando.
+
[listing]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
. Cuando se estén ejecutando todos los POD, verifique el éxito de la instalación mediante la recuperación de la instancia de AstraControlCenter instalada por el operador ACC.
+
[listing]
----
kubectl get acc -o yaml -n netapp-acc
----
. Compruebe la `status.deploymentState` en la respuesta para `Deployed` valor. Si la implementación no se realizó correctamente, aparece en su lugar un mensaje de error.
+

NOTE: Utilizará la `uuid` en el siguiente paso.

+
[listing, subs="+quotes"]
----
apiVersion: v1
items:
- apiVersion: astra.netapp.io/v1
  kind: AstraControlCenter
  metadata:
    creationTimestamp: "2021-07-28T21:36:49Z"
    finalizers:
    - astracontrolcenter.netapp.io/finalizer
   generation: 1
    name: astra
    namespace: netapp-acc
    resourceVersion: "27797604"
    selfLink: /apis/astra.netapp.io/v1/namespaces/netapp-acc/astracontrolcenters/astra
    uid: 61cd8b65-047b-431a-ba35-510afcb845f1
  spec:
    accountName: Example
    astraAddress: astra.example.com
    astraResourcesScaler: "Off"
    astraVersion: 21.08.52
    autoSupport:
      enrolled: false
    email: admin@example.com
    firstName: SRE
    lastName: Admin
    imageRegistry:
      name: registry_name/astra
  status:
    certManager: deploy
    *deploymentState: Deployed*
    observedGeneration: 1
    observedVersion: 21.08.52
    postInstall: Complete
    *uuid: c49008a5-4ef1-4c5d-a53e-830daf994116*
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
----
. Para obtener la contraseña única que utilizará cuando inicie sesión en Astra Control Center, copie la `status.uuid` valor de la respuesta en el paso anterior. La contraseña es `ACC-` Seguido del valor UUID (`ACC-[UUID]` o, en este ejemplo, `ACC-c49008a5-4ef1-4c5d-a53e-830daf994116`).




== Inicie sesión en la interfaz de usuario de Astra Control Center

Después de instalar ACC, cambiará la contraseña del administrador predeterminado e inicie sesión en el panel de interfaz de usuario de ACC.

.Pasos
. En un explorador, introduzca el FQDN que utilizó en `astraAddress` en la  `astra_control_center_min.yaml` CR cuando <<Instalar Astra Control Center,Ha instalado ACC>>.
. Acepte los certificados autofirmados cuando se le solicite.
+

NOTE: Se puede crear un certificado personalizado después de iniciar sesión.

. En la página de inicio de sesión de Astra Control Center, introduzca el valor utilizado `email` pulg `astra_control_center_min.yaml` CR cuando <<Instalar Astra Control Center,Ha instalado ACC>>, seguido de la contraseña única (`ACC-[UUID]`).
+

NOTE: Si introduce una contraseña incorrecta tres veces, la cuenta de administrador se bloqueará durante 15 minutos.

. Seleccione *Iniciar sesión*.
. Cambie la contraseña cuando se le solicite.
+

NOTE: Si este es su primer inicio de sesión y olvida la contraseña y aún no se han creado otras cuentas de usuario administrativas, comuníquese con el servicio de soporte de NetApp para obtener ayuda para la recuperación de contraseñas.

. (Opcional) quite el certificado TLS autofirmado existente y sustitúyalo por un link:../get-started/add-custom-tls-certificate.html["Certificado TLS personalizado firmado por una entidad de certificación (CA)"].




== Solucione los problemas de instalación

Si alguno de los servicios está en `Error` puede inspeccionar los registros. Busque códigos de respuesta API en la gama 400 a 500. Esos indican el lugar donde ocurrió un fracaso.

.Pasos
. Para inspeccionar los registros del operador de Astra Control Center, introduzca lo siguiente:
+
[listing]
----
kubectl logs --follow -n netapp-acc-operator $(kubectl get pods -n netapp-acc-operator -o name)  -c manager
----




== El futuro

Complete la implementación llevando a cabo link:setup_overview.html["tareas de configuración"].
