---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: Los problemas conocidos identifican problemas por los que el uso correcto de esta versión del producto puede resultar imposible. 
---
= Problemas conocidos con esta versión
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


Los problemas conocidos identifican problemas por los que el uso correcto de esta versión del producto puede resultar imposible.

Los siguientes problemas conocidos afectan a la versión actual:

* <<ClusterRoleBinding incorrecto creado por Astra Control Center CRD durante la instalación>>
* <<La aplicación con etiqueta definida por el usuario pasa al estado "eliminado">>
* <<No se puede detener la ejecución de la copia de seguridad de la aplicación>>
* <<La copia de seguridad o la clonación fallan en las aplicaciones que utilizan PVC con unidades decimales en Astra Control Center>>
* <<La interfaz de usuario de Astra Control Center se ralentiza para mostrar los cambios en los recursos de las aplicaciones, como los cambios de volúmenes persistentes>>
* <<Durante la restauración de aplicaciones a partir del backup, Trident crea un VP mayor que el VP original>>
* <<Rendimiento de clonado afectado por volúmenes persistentes de gran tamaño>>
* <<Los clones de aplicaciones producen un error al utilizar una versión específica de PostgreSQL>>
* <<Error en los clones de aplicaciones al utilizar restricciones de contexto de seguridad OCP de nivel de cuenta de servicio (SCC)>>
* <<Los bloques de S3 de Astra Control Center no informan sobre la capacidad disponible>>
* <<La reutilización de cubos entre instancias de Astra Control Center provoca fallos>>
* <<Al seleccionar un tipo de proveedor de cubos con credenciales para otro tipo, se producen fallos de protección de datos>>
* <<Es posible que no se conserven las copias de Snapshot durante la eliminación de una instancia de Astra Control Center>>
* <<Los backups adicionales se retienen como parte del backup programado>>
* link:known-issues.html#clone-operation-cant-use-other-buckets-besides-the-default["La operación de clonado no puede utilizar otros bloques además del valor predeterminado"]
* <<La administración de un clúster con Astra Control Center falla cuando el archivo kubeconfig predeterminado contiene más de un contexto>>
* link:known-issues.html#cant-determine-asup-tar-bundle-status-in-scaled-environment["No se puede determinar el estado del paquete ASUP tar en un entorno a escala"]
* <<La desinstalación de Astra Control Center no puede limpiar el módulo de control del operador de supervisión en el clúster gestionado>>
* <<La desinstalación de Astra Control Center no limpia los CRD de Traefik>>
* <<La recogida de ASUP se ha atascado en un estado de generación o carga>>




== ClusterRoleBinding incorrecto creado por Astra Control Center CRD durante la instalación

Aplique el siguiente parche a todos los clústeres de Kubernetes en los que se haya implementado la versión 21.08.65 del operador ACC. También debe aplicarse si el operador ACC se vuelve a desplegar.

Para resolver este problema:

. Sustituya `ACC_NAMESPACE` en la secuencia de comandos siguiente con el espacio de nombres al que se utilizó link:../get-started/install_acc.html#install-astra-control-center["Ponga en marcha Astra Control Center"].
+
[source, cli]
----
cat <<EOF | kubectl apply -f –
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acc-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acc-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: netapp-acc-operator
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ACC_NAMESPACE
EOF
----
. Ejecute el script.


El parche elimina los dos temas siguientes `ClusterRoleBinding: "acc-operator-manager-rolebinding"`

[listing]
----
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- apiGroup: ""
  kind: Group
  name: system:serviceaccounts
----


== La aplicación con etiqueta definida por el usuario pasa al estado "eliminado"

Si define una aplicación con una etiqueta k8s no existente, Astra Control Center creará, gestionará y eliminará inmediatamente la aplicación. Para evitarlo, añada la etiqueta k8s a pods y recursos después de que Astra Control Center gestione la aplicación.



== No se puede detener la ejecución de la copia de seguridad de la aplicación

No existe ninguna forma de detener un backup en ejecución. Si necesita eliminar el backup, espere hasta que se haya completado y, a continuación, utilice las instrucciones de link:../use/protect-apps.html#delete-backups["Eliminar backups"]. Para eliminar una copia de seguridad fallida, utilice link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["API de Astra"^].



== La copia de seguridad o la clonación fallan en las aplicaciones que utilizan PVC con unidades decimales en Astra Control Center

Los volúmenes creados con unidades decimales fallan con el proceso de copia de seguridad o clonación de Astra Control Center. Consulte link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Backup_or_clone_may_fail_for_applications_using_PVCs_with_decimal_units_in_Astra_Control_Center["artículo de base de conocimientos"] si quiere más información.



== La interfaz de usuario de Astra Control Center se ralentiza para mostrar los cambios en los recursos de las aplicaciones, como los cambios de volúmenes persistentes

Después de una operación de protección de datos (clonado, backup, restauración) y un cambio de tamaño posterior de volumen persistente, se demora hasta veinte minutos antes de que se muestre el tamaño del nuevo volumen en la interfaz de usuario. Este retraso en la interfaz de usuario también puede producirse cuando se agregan o modifican recursos de la aplicación. En este caso, una operación de protección de datos se realiza correctamente en minutos y se puede usar el software de gestión del back-end de almacenamiento para confirmar el cambio de tamaño del volumen.



== Durante la restauración de aplicaciones a partir del backup, Trident crea un VP mayor que el VP original

Si cambia el tamaño de un volumen persistente después de crear un backup y luego se restaura a partir de ese backup, el tamaño del volumen persistente coincide con el nuevo tamaño del VP en lugar de usar el tamaño del backup.



== Rendimiento de clonado afectado por volúmenes persistentes de gran tamaño

Los clones de volúmenes grandes y consumidos pueden ser intermitentemente lentos, dependiendo del acceso del clúster al almacén de objetos. Si el clon se bloquea y no se han copiado datos durante más de 30 minutos, Astra Control finaliza la acción clonada.



== Los clones de aplicaciones producen un error al utilizar una versión específica de PostgreSQL

Los clones de aplicaciones dentro del mismo clúster fallan constantemente con el gráfico BitNami PostgreSQL 11.5.0. Para clonar correctamente, utilice una versión anterior o posterior del gráfico.



== Error en los clones de aplicaciones al utilizar restricciones de contexto de seguridad OCP de nivel de cuenta de servicio (SCC)

Un clon de aplicación podría fallar si las restricciones de contexto de seguridad originales están configuradas en el nivel de cuenta de servicio dentro del espacio de nombres en el clúster OCP. Cuando se produce un error en el clon de la aplicación, aparece en el área aplicaciones gestionadas del Centro de control de Astra con el estado `Removed`. Consulte https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["artículo de base de conocimientos"] si quiere más información.



== Los bloques de S3 de Astra Control Center no informan sobre la capacidad disponible

Antes de realizar una copia de seguridad o clonar aplicaciones gestionadas por Astra Control Center, compruebe la información de los bloques en el sistema de gestión ONTAP o StorageGRID.



== La reutilización de cubos entre instancias de Astra Control Center provoca fallos

Si intenta reutilizar un cucharón utilizado por otra instalación o anterior de Astra Control Center, la copia de seguridad y la restauración fallarán. Debe utilizar un cucharón diferente o limpiar completamente el cucharón usado anteriormente. No se pueden compartir bloques entre instancias de Astra Control Center.



== Al seleccionar un tipo de proveedor de cubos con credenciales para otro tipo, se producen fallos de protección de datos

Cuando agregue un cubo, seleccione el tipo de proveedor de cucharón correcto con las credenciales que sean correctas para ese proveedor. Por ejemplo, la interfaz de usuario acepta ONTAP S3 de NetApp como el tipo con credenciales de StorageGRID; sin embargo, esto hará que se produzcan errores en todos los backups y las restauraciones futuras de aplicaciones que utilizan este bloque.



== Es posible que no se conserven las copias de Snapshot durante la eliminación de una instancia de Astra Control Center

Si dispone de una licencia de evaluación, asegúrese de almacenar su ID de cuenta para evitar la pérdida de datos en caso de que se produzca un error en Astra Control Center si no envía los ASUP.



== Los backups adicionales se retienen como parte del backup programado

A veces, uno o varios backups de Astra Control Center se retienen más allá del número especificado para retener en el programa de copia de seguridad. Estos backups adicionales deben eliminarse como parte de un backup programado, pero no se eliminan y quedan bloqueados en un `pending` estado. Para resolver el problema: https://docs.netapp.com/us-en/astra-automation-2108/workflows/wf_delete_backup.html["forzar eliminación"] los backups adicionales.



== La operación de clonado no puede utilizar otros bloques además del valor predeterminado

Durante una copia de seguridad de la aplicación o una restauración de la aplicación, puede especificar un ID de bloque. Sin embargo, en una operación de clonado de aplicaciones, siempre se utiliza el bloque predeterminado que se ha definido. No existe ninguna opción para cambiar bloques para un clon. Si desea controlar qué segmento se utiliza, puede hacer lo mismo link:../use/manage-buckets.html#edit-a-bucket["cambiar el valor predeterminado del segmento"] o haga un link:../use/protect-apps.html#create-a-backup["Backup"] seguido de un link:../use/restore-apps.html["restaurar"] por separado.



== La administración de un clúster con Astra Control Center falla cuando el archivo kubeconfig predeterminado contiene más de un contexto

No puede utilizar una imagen de kubeconfig con más de un clúster y contexto en él. Consulte link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["artículo de base de conocimientos"] si quiere más información.



== No se puede determinar el estado del paquete ASUP tar en un entorno a escala

Durante la recogida de ASUP, el estado del paquete en la interfaz de usuario se informa como o. `collecting` o. `done`. La recopilación puede tardar hasta una hora en entornos grandes. Durante la descarga de ASUP, es posible que la velocidad de transferencia del archivo de red del paquete sea insuficiente y es posible que el tiempo de espera de la descarga se agote después de 15 minutos sin indicación en la interfaz de usuario. Los problemas de descarga dependen del tamaño de ASUP, el tamaño del clúster escalado y si el tiempo de recogida supera el límite de siete días.



== La desinstalación de Astra Control Center no puede limpiar el módulo de control del operador de supervisión en el clúster gestionado

Si no ha desgestionar los clústeres antes de desinstalar Astra Control Center, puede eliminar manualmente los POD del espacio de nombres para la supervisión de netapp y el espacio de nombres con los siguientes comandos:

.Pasos
. Eliminar `acc-monitoring` agente:
+
[listing]
----
oc delete agents acc-monitoring -n netapp-monitoring
----
+
Resultado:

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Elimine el espacio de nombres:
+
[listing]
----
oc delete ns netapp-monitoring
----
+
Resultado:

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. Confirme los recursos eliminados:
+
[listing]
----
oc get pods -n netapp-monitoring
----
+
Resultado:

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. Confirme que se ha eliminado el agente de supervisión:
+
[listing]
----
oc get crd|grep agent
----
+
Resultado de la muestra:

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. Eliminar información de definición de recursos personalizada (CRD):
+
[listing]
----
oc delete crds agents.monitoring.netapp.com
----
+
Resultado:

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




== La desinstalación de Astra Control Center no limpia los CRD de Traefik

Puede eliminar manualmente los CRD de Traefik:

.Pasos
. Confirme qué CRD no se han eliminado mediante el proceso de desinstalación:
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
Respuesta

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. Eliminar CRD:
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us
----




== La recogida de ASUP se ha atascado en un estado de generación o carga

Si se mata o reinicia un pod de ASUP, es posible que una recogida de ASUP se atasque en un estado de generación o carga. Realice lo siguiente link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["API REST de Astra Control"] llamar para iniciar de nuevo la recopilación manual:

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /Accounts/{accountID}/core/v1/asups 
|===

NOTE: Esta solución de API solo funciona si se realiza más de 10 minutos después del inicio de ASUP.



== Obtenga más información

* link:../release-notes/known-limitations.html["Limitaciones conocidas de esta versión"]

